### ISSUE TITLE
치지직 클립 주소 변경으로 인한 카페에서 재생 불가

### ISSUE THREAD

**Issue by qudtj5894** [nomomo/Naver-Cafe-Twitch-Clip-Loader#10]
**귀하의 기능 요청이 문제와 관련되어 있습니까? 설명해주세요.**
8월1일 치지직 클립 업데이트로 인한 클립 주소 형식이 변경되어 카페에서 바로 재생이 불가합니다
원래 치지직 클립의 주소 형식은 https://chzzk.naver.com/embed/clip/123456 이였는데
이번 클립 업데이트 후 치지직 클립의 주소 형식이 https://chzzk.naver.com/clips/123456으로 변경 되었습니다

**원하는 솔루션을 설명하세요**
새로 바뀐 클립 주소의 형식을 추가해주시면 좋을거 같습니다
다만 이전 주소 형식(https://chzzk.naver.com/embed/clip/123456)을 제거 후 현재 주소 형식으로 바꿀 경우 
8월1일 이전에 카페에 올린 클립은 바로 볼 수가 없어지므로 이전 주소 형식을 유지하면서 현재 주소 형식을 추가해주시면 
좋을거 같습니다

첫번째 사진이 이전 주소 형식
![화면 캡처 2024-08-07 021250](https://github.com/user-attachments/assets/006229df-b20c-4125-8c47-0899fe608dee)

두번째 사진이 현재 주소 형식
![화면 캡처 2024-08-07 021315](https://github.com/user-attachments/assets/a331eb2d-c690-4132-9378-88dfab04ba32)

**Comment by nomomo** [comment]
안녕하세요. 제보 감사드립니다.
1.4.2 버전에서 수정되었으며 다음 링크에서 업데이트 부탁드려요! [https://github.com/nomomo/Naver-Cafe-Twitch-Clip-Loader/raw/main/Naver-Cafe-Clip-Loader.user.js](https://github.com/nomomo/Naver-Cafe-Twitch-Clip-Loader/raw/main/Naver-Cafe-Clip-Loader.user.js)
