### ISSUE TITLE
SOOP 클립과 VOD에 추가된 챕터 기능의 미적용 문제

### ISSUE THREAD

**Issue by TheDebuffer** [nomomo/Naver-Cafe-Twitch-Clip-Loader#12]
**귀하의 기능 요청이 문제와 관련되어 있습니까? 설명해주세요.**
문제가 무엇인지에 대한 명확하고 간결한 설명입니다. 전. 나는 항상 좌절할 때 [...]

아프리카TV가 SOOP으로 개편되면서 클립과 VOD에 챕터기능이 추가되었습니다. 그런데 유튜브 동영상의 챕터기능은 정상적으로 작동하는데 비해 SOOP 클립의 챕터기능이 전혀 동작하지 않습니다.

**원하는 솔루션을 설명하세요**
당신이 원하는 일에 대한 명확하고 간결한 설명.

비디오 업로더가 설정한 챕터기능을 사용할 수 있었으면 좋겠습니다.

**고려한 대안을 설명하세요**
고려한 대체 솔루션이나 기능에 대한 명확하고 간결한 설명.

**추가 상황**
여기에 기능 요청에 대한 다른 컨텍스트나 스크린샷을 추가하세요.

**Comment by nomomo** [comment]
안녕하세요. SOOP 에서 제공하는 EMBED 플레이어(외부 사이트에서 VOD를 플레이하기 위한 플레이어)에서는 챕터 기능을 지원하지 않습니다.
먼저 SOOP에 개선 요청을 하시는 것이 좋을 듯합니다.

코드를 잠깐 뜯어봤는데 embed player 에서 쉽게 chapter 기능을 on-off 할 수 있는 flag 같은 것을 찾기가 어렵네요.
챕터 정보를 파싱한 다음 챕터 기능이 포함된 progress bar(multiprogress)를 직접 구현할 수도 있는데요. 필요성에 비해 들여야 하는 수고가 많고, 개편 초기라 플레이어 구조 변경이 잦을텐데 이렇게 변경될 때마다 이에 맞게 대응해줘야 하는 등의 문제가 있네요 ㅜㅜ.

**Comment by TheDebuffer** [comment]
피드백 감사합니다. SOOP에 먼저 문의를 넣어보는게 맞겠네요. 최근 리브랜딩 이후 여러 개선패치 같은 것들이 넘어오는데도 빠르게 피드백 받아주시고 대응패치 내주시는게 대단한것 같습니다. 감사합니다.
