### ISSUE TITLE
클리피 종료 예정으로 지원 대상에서 제외 요청

### ISSUE THREAD

**Issue by dokdo2013** [nomomo/Naver-Cafe-Twitch-Clip-Loader#7]
안녕하세요, 클리피 개발자입니다.

안타깝게도 [클리피](https://clippy.kr) 서비스를 2023년 2월 14일 21시에 종료하게 됨에 따라, 제작해주신 스크립트에서 클리피 기능 제외를 요청드립니다. ([공지사항](https://verbose-spot-25e.notion.site/7eaf3adb36764480937b3a38d3c5d4bc) 참고)
종료일 이후부터는 임베드 플레이어를 포함한 모든 서비스의 이용이 불가하니 이 점 참고 부탁드립니다.

감사합니다.

**Comment by nomomo** [comment]
이슈 남겨주셔서 감사합니다. 오늘 커밋된 1.0.7 버전부터 Clippy 변환 기능은 제외됩니다. 그간 좋은 서비스 개발 운영 하시느라 고생 많으셨습니다.
