### ISSUE TITLE
게시판 글 기본 표시 개수 설정 -> 기본값 사용일 때만 인기글 보이는 버그

### ISSUE THREAD

**Issue by yayokorea** [nomomo/Naver-Cafe-Twitch-Clip-Loader#9]
_깃허브 처음 써봐서 이렇게 제보하는 게 맞는지 모르겠지만 일단 써봅니다.
평소에 게시판 글 기본 표시 개수 30개로 쓰는 데 인기글이 안보여서 제보합니다
https://cafe.naver.com/ca-fe/cafes/27842958/popular 이 링크로 들어가면 보이긴 합니다_

_프로그래밍에 대해 아는 건 없지만 왜 이러는지 추측해보면
인기글을 우클릭하고 링크 주소를 복사하면 https://cafe.naver.com/ca-fe/cafes/27842958/popular&userDisplay=30
이렇게 복사가 되는데 '&userDisplay=30' 이 부분 때문에 안 보이는 게 아닐까 합니다. 이 부분을 지우면 제대로 보입니다.
빠르게 고쳐주시면 감사할 것 같습니다!_

**버그 설명**
게시판 글 기본 표시 개수 설정 -> 기본값 사용일 때만 인기글 보이는 버그입니다

**재현용**
동작을 재현하는 단계:
1. 설정으로 이동
2. 편의 기능 -> 게시판 글 기본 표시 개수 설정 -> 기본값 사용 외 다른 것을 클릭하세요.
3. 카페의 인기글 클릭하세요.
4. 오류 보기

**스크린샷**
https://cdn.discordapp.com/attachments/974921391340126269/1159049021277610055/image.png?ex=651e7804&is=651d2684&hm=878f1170a8fcbfb1c66548354c454a360004816187949119acd84e35bf4aae55&

**데스크톱(다음 정보를 작성해 주세요):**
  - OS : Windows11
  - 브라우저 : 크롬
  - 버전 117.0.5938.132

**Comment by nomomo** [comment]
v1.3.1 버전에서 수정 완료 했습니다. 제보 감사드려요!!
